redditclone/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/', views.signup, name = 'signup'),
    url(r'^login/', views.loginview, name = 'login'),
]

redditclone/posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^create/', views.create, name = 'create'),
    url(r'(?P<pk>[0-9]+/upvote)', views.upvote, name='upvote'),
]

redditclone/redditclone/urls.py
from django.contrib import admin
from django.conf.urls import url, include

from posts import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^$', views.home, name = "home" ),
    ]

redditclone/posts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    url = models.TextField()
    pub_date = models.DateTimeField()
    author  = models.ForeignKey(User)
    votes_total = models.IntegerField(default = 1)


    def __str__(self):
            return self.title

redditclone/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

# Create your views here.
def signup(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.get(username = request.POST['username'])
                return render(request, 'accounts/signup.html', {'error':'Username already taken'})
            except User.DoesNotExist:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                login(request, user)
                return render(request, 'accounts/signup.html')
        else:
            return render(request, 'accounts/signup.html', {'error':'Passwords didn\'t match'})
    else:
        return render(request, 'accounts/signup.html')

def loginview(request):
    if request.method == 'POST':
        user = authenticate(username = request.POST['username'], password = request.POST['password'])
        if user is not None:
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            return render(request, 'accounts/login.html', {'error':'Login successful'})

        else:
            return render(request, 'accounts/login.html', {'error':'Username and Password didn\'t match'})
    else:
        return render(request, 'accounts/login.html')

redditclone/posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Post
# Create your views here.
@login_required
def create(request):
    if request.method == 'POST':
        if request.POST['title'] and request.POST['url']:
            post = Post()
            post.title = request.POST['title']
            if request.POST['url'].startswith('http://') or request.POST['url'].startswith('https://'):
                post.url = request.POST['url']
            else:
                post.url = 'http://'+ request.POST['url']

            post.author = request.user
            post.pub_date = timezone.datetime.now()
            post.save()
            return redirect('home')
        else:
            return render(request, 'posts/create.html', {'error': 'ERROR: You must include a title and url to create a post.'})

    else:
        return render(request, 'posts/create.html')


def home(request):
    posts = Post.objects.order_by('votes_total')
    return render(request, 'posts/home.html', {'posts':posts})

def upvote(request, pk):
    post = Post.objects.get(pk=pk)
    post.votes_total += 1
    post.save()
    return redirect('home')

redditclone/accounts/templates/accounts/login.html
<h1>Log In</h1>
{% if error %}
{{ error }}
<br/>
<br/>
{% endif %}

<form method="POST" action="{% url 'accounts:login' %}">
  {%csrf_token%}

  {% if request.GET.next %}
  <input type="hidden" name="next" value={{request.GET.next}}/>
  {% endif %}

  Username:
  <br/>
  <input type="text" name="username"/>
  <br/>
  Password:
  <br/>
  <input type="password" name="password"/>
  <br/>
  <input type="submit" value="Login"/>
</form>

redditclone/accounts/templates/accounts/signup.html
<h1>Sign Up</h1>
{% if error %}
{{ error }}
<br/>
<br/>
{% endif %}

<form method="POST" action="{% url 'accounts:signup' %}">
  {%csrf_token%}
  Username:
  <br/>
  <input type="text" name="username"/>
  <br/>
  Password:
  <br/>
  <input type="password" name="password1"/>
  <br/>
  Confirm Password:
  <br/>
  <input type="password" name="password2"/>
  <br/>
  <input type="submit" value="Sign Up"/>
</form>

redditclone/posts/templates/posts/create.html
<h1>New Post</h1>
{% if error %}
{{ error }}
<br/>
<br/>
{% endif %}

<form method="POST" action="{% url 'posts:create' %}">
  {%csrf_token%}

  Title:
  <br/>
  <input type="text" name="title"/>
  <br/>
  URL:
  <br/>
  <input type="text" name="url"/>
  <br/>
  <input type="submit" value="Post"/>
</form>

redditclone/posts/templates/posts/home.html
<h1>Nowhere</h1>
<a href= "{%url 'posts:create' %}">New Post</a>

<br/>
<br/>

{% for post in posts.all %}

<a>UP</a> {{ post.votes_total }} <a>DOWN</a> - <a href="{{ post.url }}">{{ post.title }}</a>
<br/>
{{ post.pub_date }} by {{ post.author.username }}
<br/>
<br/>

{% endfor %}